export { default as Shop } from "./Shop";
export { default as Home } from "./Home";
export { default as Blog } from "./Blog/BlogRouter";
export { default as Sponsors } from "./Sponsors";
export { default as BusinessPlan } from "./BusinessPlan";
export { default as Philosophy } from "./Philosophy";
export { default as ContactUs } from "./ContactUs";
export { default as Support } from "./Support";
export { default as Measurements } from "./Measurements";
